### ISSUE TITLE
Users are able to delete the text written by the OS in the Q OS Command Line

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-OS#1]
When the initial command line prompt is issued in the Q OS Terminal, users are able to simply hold the backspace key to delete the:

<code>Q Kernel> </code>

Text at the start of each command line.

**Comment by raphydaphy** [comment]
This issue is fixed in Update 3

**Comment by faizaanceg** [comment]
You can close issues automatically when committing with messages like `fixes #1` or `closes #1, #2` in your commit messages. Saves you a bit of time.

**Comment by raphydaphy** [comment]
Thanks :)

Can't you just press Close & Comment though?

**Comment by raphydaphy** [comment]
oh i get what you mean now :)

**Comment by faizaanceg** [comment]
:+1:
