### ISSUE TITLE
Nothing works in Update 3.1

### ISSUE THREAD

**Issue by raphydaphy** [raphydaphy/Q-OS#10]
After downloading the Update 3.1 code, the <code>readStr()</code> function is broken and so pretty much everything in Q OS does not work.

Don't download the 3.1 files...

**Comment by faizaanceg** [comment]
Shouldn't `#include "inc/kb."` be `#include "inc/kb.h"`?

Ref: https://github.com/raphydaphy/Q-OS/blob/master/kernel/kernel.c#L1

**Comment by raphydaphy** [comment]
Yes

I changed that in my personal copy of the code already but forgot to push it to GitHub. Thanks for your reply.

**Comment by faizaanceg** [comment]
:+1:

**Comment by raphydaphy** [comment]
But it dosen't fix the problem ): 

I have no idea what I did wrong iam confused

**Comment by faizaanceg** [comment]
Is that the only function which doesn't work?

**Comment by raphydaphy** [comment]
<code>print()</code> is working and thats the only other one i tested

**Comment by faizaanceg** [comment]
https://github.com/raphydaphy/Q-OS/blob/master/kernel/inc/kb.c#L351

There are no `break` statements for 2 cases. I don't know how much they help. I don't have the code locally so can't test.

**Comment by raphydaphy** [comment]
Can't you clone the repo in git? Or did I type some bad thing that made it so noone can?

**Comment by raphydaphy** [comment]
I'll try adding the break's tho it might help

**Comment by faizaanceg** [comment]
@raphydaphy  chill mate =) . I am on Windows right now, so can't build it.

**Comment by raphydaphy** [comment]
O rip

**Comment by raphydaphy** [comment]
Wow i just tried running with the iso in virtualbox and it worked wtfff

**Comment by raphydaphy** [comment]
qemu = nowork
virtualbox = work

**Comment by faizaanceg** [comment]
:+1:

**Comment by raphydaphy** [comment]
**this is fixed by running the OS in virtualbox instead of qemu**
