### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by stanfordude** [raphydaphy/Q-OS#11]
Small Issue,  but if you want to encourage others to help out more,  try organizing the project file structure and names in a readable format. I.E instead of string.c. Maybe stringUtils.c and etc. .  Good job so far though!

**Comment by raphydaphy** [comment]
Thanks, I will do that. 

Today I (think) i improved the readability by adding .c files for the header files in /inc/..

I'll rename some files so they make more sense and also add some more comments because there aren't many at the moment. :disappointed:

**Comment by raphydaphy** [comment]
I have fixed this now, in Update 1.3

**Comment by raphydaphy** [comment]
But i haven't added comments so i'll keep this open

**Comment by raphydaphy** [comment]
https://github.com/raphydaphy/Q-OS/wiki/Documentation

I started working on this file ^ to make the code potentially easier to read and edit. It's not finished though as I've only written the first section so far.

**Comment by raphydaphy** [comment]
I think that we are doing good at readability now so I will close this
