### ISSUE TITLE
Unhelpful commit messages when browsing github commit history

### ISSUE THREAD

**Issue by Barteks2x** [raphydaphy/Q-OS#13]
I think these commit messages are a bit unreadable when you browse commit gistory on github - the first line is always Create/Update/Delete Filename. It doesn't tell much about what has been changed in that commit.
for example this commit: https://github.com/raphydaphy/Q-OS/commit/bb8f44bf28746a1c3f09b032754dd74e76144728 has message:

    Update kernel.c
    (Update 3) Fixed the issue with users being able to delete the kernel command prompt

But github commit history shows only 

    Update kernel.c

Messages like "Update fileX" are a bit reduntant - git already keeps track of which files are changed in which commit.

**Comment by raphydaphy** [comment]
I only put commit descriptions in the bit that said "Description" which is why this happens, from now on I will put the thing I changed in the commit name instead :+1:

**Comment by raphydaphy** [comment]
Sorry for super long reply time, I spent all day trying to setup a cross compiler ): 

Still not working

**Comment by Barteks2x** [comment]
So you are using some GUI for git, right? I use commandline and I know that the first line is shown on github commit history and others are shown when viewing that commit. And you can change multiple files in single commit (you never did that so I assume you might not know that).
When I first used git I used some weird GUI that created separate commit for each changed file, so it may be what happens here too.

**Comment by raphydaphy** [comment]
I just use github.com

Is that bad :worried:

**Comment by faizaanceg** [comment]
You can do it from the commandline. Way easier

**Comment by raphydaphy** [comment]
I tried and it was confusing...

I will try again :)
