### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Rocket-Scientist2** [raphydaphy/Q-OS#19]
In the second paragraph of "Tiny Files", you spelt "century" wrong.
:P gl

**Comment by plankp** [comment]
I'll close this issue when I fix it. Thank you for find typos. Check for more of them!

**Comment by raphydaphy** [comment]
Wow hi cole :)

**Comment by raphydaphy** [comment]
I fixed this :)

Read the commit description for extra points :+1:

**Comment by raphydaphy** [comment]
^ i added a new lable called typo for issues like this
